name: Invia email feedback albergatore

on:
  issues:
    types: [opened]

jobs:
  send-email:
    if: contains(github.event.issue.labels.*.name, 'feedback')
    runs-on: ubuntu-latest
    steps:
      - name: Invia email a mario@in3pida.it
        uses: dawidd6/action-send-email@v3
        with:
          server_address: ${{ secrets.SMTP_HOST }}
          server_port: ${{ secrets.SMTP_PORT }}
          secure: true
          username: ${{ secrets.SMTP_USER }}
          password: ${{ secrets.SMTP_PASS }}
          subject: "Feedback ISI: ${{ github.event.issue.title }}"
          body: "${{ github.event.issue.body }}"
          to: mario@in3pida.it
          from: "Eletta ISI <info@in3pida.com>"
